POST http://127.0.0.1:3000/event
Content-Type: application/json

{
  "name": "Barcelona Trip",
  "goal": 130000,
  "deadline": "2024-09-23T13:35:47Z"
}

###
POST http://127.0.0.1:3000/savings
Content-Type: application/json

{
  "name": "Trip to France",
  "goal": 100000,
  "deadline": "2024-11-14T13:35:47Z",
  "months": 2,
  "participants": [{
    "account_id": "1",
    "first_name": "Luis",
    "last_name": "Amado",
    "percentage": 0.5
  }, {
    "account_id": "2",
    "first_name": "Fer",
    "last_name": "Moran",
    "percentage": 0.5
  }]
}

###
GET http://127.0.0.1:3000/events_savings?account_id=1
Content-Type: application/json

###
POST http://127.0.0.1:3000/chat
Content-Type: application/json

{
  "event_id": "66e60dc24645973fb256c706",
  "author_id": "1",
  "author": "Luis",
  "content": "Hola como estan 123?"
}

###
POST http://127.0.0.1:3000/poll
Content-Type: application/json

{
  "event_id": "66e60dc24645973fb256c706",
  "author_id": "1",
  "author": "Luis",
  "title": "Do you want to go first class?",
  "options": [{
    "name": "Yes",
    "cost": 50000
  },{
    "name": "No",
    "cost": 0
  }]
}